### ISSUE TITLE
[node-routing] Link to http docs

### ISSUE THREAD

**Issue by andrewMacmurray** [FAC7/READMEs#92]
The link takes me to the learning outcomes for week4 READMEs, should this go here: https://nodejs.org/api/http.html instead?

**Comment by franzmoro** [comment]
the link should point to the http readme tutorial/folder. we created the link before the folder was pushed to the repo.

**Comment by franzmoro** [comment]
commit 2ac8301db3e7c00b1c418e1f1b108320cb47a017

**Comment by andrewMacmurray** [comment]
:+1:
